name: Latest beta environment preflight
permissions:
  contents: read
jobs:
  macos-tests:
    name: macOS tests
    uses: rksharma-owg/swift-service-context/.github/workflows/macos_tests.yml@main
    with:
      runner_pool: general
      build_scheme: swift-service-context-Package
      swift_6_2_enabled: false
      swift_6_3_enabled: false
      swift_6_4_enabled: false
      xcode_latest_beta_enabled: true
'on':
  workflow_dispatch:
    inputs:
      patch_sha:
        type: string
        required: true
      base_sha:
        type: string
        required: true
